spring : 
  application:
    name : SERVICE-REGISTERY
  
eureka :
  instance :
    hostname : localhost
  
  client :
    fetch-registry : false
    register-with-eureka : false
 
server:
  port: 9090