spring :
  application:
    name : USER-SERVICE  
  data :
    mongodb :
      url : mongodb://localhost:27017
      database: microservices
  config:
    import: "optional:configserver:http://localhost:8888"

server:
  port: 8080

