spring :
  application:
    name : USER-SERVICE  
  data :
    mongodb :
      url : mongodb://localhost:27017
      database: microservices
  config:
    import: "optional:configserver:http://localhost:8888"

server:
  port: 8080

#####RESILence 4J configuration for Circuit breaker
management: health:   circuitbreakers:     enabled: true 
 endpoints:   web:     exposure:       include: health endpoint:   health:     show-details: always
     
resilience4j:
  circuitbreaker:
    instances:
      userCareerServiceBreaker :
        registerHealthIndicator: true        event-consumer-buffer-size: 10
        failure-rate-threshold: 10
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED 