spring :
  application:
    name : CAREER-SERVICE  
  data :
    mongodb :
      url : mongodb://localhost:27017
      database: careerservice
      
server:
  port: 8081


eureka: 
  client :
    enabled : true
    fetch-registry : true
    register-with-eureka: true
    service-url: 
      defaultZone : http://localhost:9090/eureka
      
      
  instance:
      prefer-ip-address: true 